name: untitled
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  device_preview: ^1.2.0
  curved_navigation_bar: ^1.0.1
  flutter_screenutil: ^5.3.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  flutter_settings_ui: ^3.0.1


  # Cupertino Icons for iOS style icons
  cupertino_icons: ^1.0.6

  # Include any other dependencies here
  # Example: http: ^0.13.4
  # flutter_auth: ^1.0.0 # Uncomment if you have a custom or local flutter_auth package

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, uncomment and add your assets here:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, uncomment and add your fonts here:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
