/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'shopnest_dart';
  static const String PLUGIN_VERSION = '0.0.0+1';
  static const String FORGOT = 'assets/logo/forgot.gif';
  static const String GIF = 'assets/logo/gif.gif';
  static const String MAIL = 'assets/logo/mail.gif';
  static const String SENDING = 'assets/logo/sending.gif';
}
